# Use an Ubuntu LTS release for stability
FROM ubuntu:noble-20250415.1
WORKDIR /root
# Add all needed packages here.
# RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential git gdb curl
